### ISSUE TITLE
Dockerfile not working

### ISSUE THREAD

**Issue by nmoran** [CosmiQ/CosmiQ_SN6_Baseline#1]
When trying to build a docker image from the root folder with

```
docker build .
```

Fails with the following messages

```
Executing transaction: failed                                                                                           
ERROR conda.core.link:_execute(502): An error occurred while installing package 'conda-forge::affine-2.3.0-py_0'.
FileNotFoundError(2, "No such file or directory: '/opt/conda/envs/solaris/bin/python3.6'")
Attempting to roll back.

Rolling back transaction: done

FileNotFoundError(2, "No such file or directory: '/opt/conda/envs/solaris/bin/python3.6'")
```

Appears that it is attempting to install the affine package before installing the python interpreter itself. Have found a work around which involves first creating the environment with 

```
conda create -n solaris python=3.6.7
```

And then installing the packages
```
conda install --file environment-gpu.txt
```
Where `envrionment-gpu.txt` is a flat list of the packages from the `environment-gpu.yml` file without the channel information or other structural elements.

**Comment by nrweir** [comment]
This is definitely odd given that `python=3.6` is _in_ the `solaris` environment-gpu.yml - historically that's been sufficient to get the dependencies installed as well. I'll see if I can reproduce the error...what version of `conda` are you running?

Thank you for raising the issue!

**Comment by nmoran** [comment]
Yes I found it very strange also. Think the issue is that while `python=3.6` is specified in the `environment-gpu.yml`, it attempts to install the affine package before it installs the python package or at least this is the only way I could make sense of it. 

The updates in PR #2 seem to address it.

Using Miniconda3-4.5.4 as specified in the Dockerfile

**Comment by dphogan** [comment]
We're going to hold off on implementing the pull request since we can't reproduce the error, but we'll leave this issue open to see if other people report the same issue.

I'll go ahead and fix the file path error in train.sh that you caught.

Thanks for helping us improve the baseline.

**Comment by nmoran** [comment]
Happy to hear the path fix was useful. 

Wondering how you tried to reproduce issue, which version of docker and environment as I've reproduced this issue on a number of systems.

**Comment by dphogan** [comment]
I spoke too soon -- we did indeed see the same issue.  A fix has now been implemented (adding a "conda update" command to the Dockerfile worked).
